theme: jekyll-theme-architect 

show_downloads: true

title:  Quick - Android_Device_Info

description: A Small Utility Made Using Python For Debug/QA Purposes ,You can View Info Related To Software Build Properties example - FOTA Version,Packages Etc 
